stages:
  - build
  - deploy

build-staging:
  stage: build
  image: node:16
  tags:
    - container
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  environment: staging

build-production:
  stage: build
  image: node:16
  tags:
    - container
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist-production/
    expire_in: 1 week
  environment: production
  only:
    - master